@extends('ecommerce.default')
@section('content')
<section class="py-10 md:py-14 bg-gray-50/70 min-h-screen">
<div class="container mx-auto px-4 max-w-7xl">
<div class="grid lg:grid-cols-[minmax(0,1fr)_360px] gap-7 items-start">
<div>
<div class="mb-7"><nav class="flex items-center gap-2 text-[10px] uppercase tracking-widest font-black text-gray-400 mb-3"><a href="{{$rota}}" class="hover:text-main">Início</a><span>/</span><a href="{{$rota}}/carrinho" class="hover:text-main">Carrinho</a><span>/</span><span>Cadastro</span></nav><span class="text-[10px] uppercase tracking-[.18em] font-black text-main">Etapa 1 de 3</span><h1 class="text-3xl md:text-4xl font-black tracking-[-.03em] text-gray-950 mt-2">Complete seus dados</h1><p class="text-sm text-gray-500 mt-2">Crie sua conta para continuar para endereço e pagamento.</p></div>
<div class="flex items-center gap-3 mb-6"><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-main text-white flex items-center justify-center text-xs font-black">1</span><span class="text-xs font-black text-gray-900">Dados</span></div><div class="h-px flex-1 bg-gray-200"></div><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center text-xs font-black">2</span><span class="text-xs font-black text-gray-400">Entrega</span></div><div class="h-px flex-1 bg-gray-200"></div><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center text-xs font-black">3</span><span class="text-xs font-black text-gray-400">Pagamento</span></div></div>
<form method="post" class="bg-white border border-gray-100 rounded-3xl p-5 md:p-7 shadow-sm">@csrf<input type="hidden" value="{{$default['config']->empresa_id}}" name="empresa_id"><input type="hidden" value="{{$default['carrinho']->id}}" name="pedido_id">
<div class="flex items-center justify-between gap-4 mb-6 pb-5 border-b border-gray-100"><div><h2 class="text-lg font-black text-gray-950">Seus dados</h2><p class="text-xs text-gray-500 mt-1">Campos com * são obrigatórios.</p></div><a href="{{$rota}}/login" class="text-xs font-black text-main hover:underline">Já tenho conta</a></div>
<div class="grid md:grid-cols-2 gap-4">
@php $input='w-full h-12 px-4 border border-gray-200 rounded-xl outline-none focus:border-main focus:ring-4 focus:ring-main/10 bg-white'; $label='block text-xs font-black text-gray-600 mb-2'; @endphp
<div><label class="{{$label}}">Nome *</label><input autofocus required name="nome" value="{{old('nome')}}" class="{{$input}} @error('nome') border-red-400 @enderror">@error('nome')<p class="text-xs text-red-500 mt-1">{{$message}}</p>@enderror</div>
<div><label class="{{$label}}">Sobrenome *</label><input required name="sobre_nome" value="{{old('sobre_nome')}}" class="{{$input}}">@error('sobre_nome')<p class="text-xs text-red-500 mt-1">{{$message}}</p>@enderror</div>
<div><label class="{{$label}}">Telefone *</label><input required data-mask="(00) 00000-0000" name="telefone" value="{{old('telefone')}}" type="tel" class="{{$input}}"></div>
<div><label class="{{$label}}">E-mail *</label><input required name="email" value="{{old('email')}}" type="email" class="{{$input}}"></div>
<div><label class="{{$label}}">Senha *</label><input required minlength="8" name="senha" type="password" autocomplete="new-password" class="{{$input}}"><p class="text-[10px] text-gray-400 mt-1">Use pelo menos 8 caracteres.</p></div>
<div class="grid grid-cols-[120px_minmax(0,1fr)] gap-3"><div><label class="{{$label}}">Documento *</label><select name="tp_doc" id="tp_doc" class="{{$input}}"><option value="cpf" @selected(old('tp_doc')==='cpf')>CPF</option><option value="cnpj" @selected(old('tp_doc')==='cnpj')>CNPJ</option></select></div><div><label class="{{$label}} lbl_doc">CPF *</label><input required id="doc" value="{{old('cpf')}}" name="cpf" type="tel" class="{{$input}}"></div></div>
<div class="ie hidden"><label class="{{$label}}">Inscrição Estadual *</label><input value="{{old('ie')}}" name="ie" type="tel" class="{{$input}}"></div>
</div>
<div class="mt-8 mb-5"><h2 class="text-lg font-black text-gray-950">Endereço</h2><p class="text-xs text-gray-500 mt-1">Usado como endereço inicial da sua conta.</p></div>
<div class="grid md:grid-cols-12 gap-4"><div class="md:col-span-9"><label class="{{$label}}">Rua *</label><input required value="{{$enderecoCep?$enderecoCep->logradouro:old('rua')}}" name="rua" class="{{$input}}"></div><div class="md:col-span-3"><label class="{{$label}}">Número *</label><input required value="{{old('numero')}}" name="numero" class="{{$input}}"></div><div class="md:col-span-6"><label class="{{$label}}">Bairro *</label><input required value="{{$enderecoCep?$enderecoCep->bairro:old('bairro')}}" name="bairro" class="{{$input}}"></div><div class="md:col-span-6"><label class="{{$label}}">Cidade *</label><input required value="{{$enderecoCep?$enderecoCep->localidade:old('cidade')}}" name="cidade" class="{{$input}}"></div><div class="md:col-span-2"><label class="{{$label}}">UF *</label><select required name="uf" id="uf" class="{{$input}}"><option value="">UF</option>@foreach(\App\Models\Cliente::estados() as $uf)<option value="{{$uf}}" @selected(($enderecoCep&&$enderecoCep->uf==$uf)||old('uf')==$uf)>{{$uf}}</option>@endforeach</select></div><div class="md:col-span-4"><label class="{{$label}}">CEP *</label><input required data-mask="00000-000" value="{{$default['carrinho']->observacao!=''?$default['carrinho']->observacao:old('cep')}}" name="cep" class="{{$input}}"></div><div class="md:col-span-6"><label class="{{$label}}">Complemento</label><input value="{{old('complemento')}}" name="complemento" class="{{$input}}"></div><div class="md:col-span-12"><label class="{{$label}}">Observação</label><input value="{{old('observacao')}}" name="observacao" placeholder="Ex.: deixar na portaria" class="{{$input}}"></div></div>
<div class="mt-7 pt-6 border-t border-gray-100 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><a href="{{$rota}}/carrinho" class="text-xs font-black text-gray-500 hover:text-main"><i class="fa fa-arrow-left mr-2"></i>Voltar ao carrinho</a><button type="submit" class="h-13 px-7 py-4 bg-main text-white rounded-2xl text-xs uppercase tracking-wider font-black hover:opacity-90">Salvar e continuar <i class="fa fa-arrow-right ml-2"></i></button></div>
</form></div>
<aside class="lg:sticky lg:top-28"><div class="bg-white border border-gray-100 rounded-3xl p-5 md:p-6 shadow-sm"><h2 class="text-lg font-black text-gray-950 mb-5">Resumo do pedido</h2><div class="space-y-4">@if($default['carrinho'])@foreach($default['carrinho']->itens as $i)<div class="flex gap-3 items-center"><div class="w-14 h-14 rounded-xl bg-gray-50 overflow-hidden flex-shrink-0">@if(isset($i->produto->galeria)&&count($i->produto->galeria)>0)<img src="{{$i->produto->galeria[0]->img}}" class="w-full h-full object-contain p-1">@endif</div><div class="min-w-0 flex-1"><strong class="block text-xs text-gray-800 truncate">{{$i->produto->produto->nome}}</strong><span class="text-[10px] text-gray-400">Qtd. {{$i->quantidade}}</span></div><span class="text-xs font-black whitespace-nowrap">R$ {{number_format($i->quantidade*$i->produto->valor,2,',','.')}}</span></div>@endforeach @endif</div><div class="mt-6 pt-5 border-t border-gray-100 space-y-3 text-sm"><div class="flex justify-between text-gray-500"><span>Subtotal</span><strong class="text-gray-900">R$ {{number_format($default['carrinho']->somaItens(),2,',','.')}}</strong></div><div class="flex justify-between text-gray-500"><span>Frete</span><strong class="text-gray-900">R$ {{number_format($default['carrinho']->valor_frete,2,',','.')}}</strong></div><div class="flex justify-between items-end pt-3 border-t border-gray-100"><span class="font-black text-gray-900">Total</span><strong class="text-2xl font-black text-main">R$ {{number_format($default['carrinho']->somaItens()+$default['carrinho']->valor_frete,2,',','.')}}</strong></div></div><div class="grid grid-cols-2 gap-2 mt-5"><div class="rounded-xl bg-gray-50 p-3 text-center"><i class="fa fa-lock text-main"></i><span class="block text-[9px] font-black mt-1">Compra segura</span></div><div class="rounded-xl bg-gray-50 p-3 text-center"><i class="fa fa-truck text-main"></i><span class="block text-[9px] font-black mt-1">Entrega acompanhada</span></div></div></div></aside>
</div></div></section>
@endsection
@section('javascript')
<script>$(function(){changeDoc()});$('#tp_doc').change(changeDoc);function changeDoc(){let v=$('#tp_doc').val();if(v==='cpf'){$('#doc').mask('000.000.000-00',{reverse:true});$('.lbl_doc').html('CPF *');$('.ie').addClass('hidden')}else{$('#doc').mask('00.000.000/0000-00',{reverse:true});$('.lbl_doc').html('CNPJ *');$('.ie').removeClass('hidden')}}</script>
@endsection