@extends('ecommerce.default')
@section('content')
@php
$cidadeNome='';$cidadeUf='';
if(!empty($default['config']->cidade)){$cidadeDecode=json_decode($default['config']->cidade);if($cidadeDecode){$cidadeNome=$cidadeDecode->nome??'';$cidadeUf=$cidadeDecode->uf??'';}else{$cidadeNome=$default['config']->cidade;}}
$telefone=preg_replace('/[^0-9]/','',$default['config']->telefone);if(strlen($telefone)==11){$telefone=preg_replace('/(\d{2})(\d{5})(\d{4})/','($1) $2-$3',$telefone);} 
$rua=trim((string)$default['config']->rua);$numero=trim((string)$default['config']->numero);$endereco=trim($rua.($numero?' , '.$numero:''),' ,');
@endphp
<section class="py-10 md:py-14 bg-gray-50/70 min-h-screen"><div class="container mx-auto px-4 max-w-7xl">
<div class="max-w-2xl mb-8"><span class="text-[10px] uppercase tracking-[.18em] font-black text-main">Fale conosco</span><h1 class="text-3xl md:text-4xl font-black text-gray-950 tracking-[-.03em] mt-2">Contato</h1><p class="text-sm text-gray-500 mt-2">Precisa de ajuda? Envie uma mensagem ou use um dos canais abaixo.</p></div>
<div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4 mb-8"><div class="bg-white border border-gray-100 rounded-2xl p-5"><div class="w-10 h-10 rounded-xl bg-main/10 text-main flex items-center justify-center"><i class="fa fa-phone"></i></div><span class="block text-[10px] uppercase tracking-widest font-black text-gray-400 mt-4">Telefone</span><strong class="block text-sm text-gray-900 mt-1">{{$telefone?:$default['config']->telefone}}</strong></div><div class="bg-white border border-gray-100 rounded-2xl p-5"><div class="w-10 h-10 rounded-xl bg-main/10 text-main flex items-center justify-center"><i class="fa fa-envelope"></i></div><span class="block text-[10px] uppercase tracking-widest font-black text-gray-400 mt-4">E-mail</span><strong class="block text-sm text-gray-900 mt-1 break-all">{{$default['config']->email}}</strong></div><div class="bg-white border border-gray-100 rounded-2xl p-5"><div class="w-10 h-10 rounded-xl bg-main/10 text-main flex items-center justify-center"><i class="fa fa-clock-o"></i></div><span class="block text-[10px] uppercase tracking-widest font-black text-gray-400 mt-4">Funcionamento</span><strong class="block text-sm text-gray-900 mt-1">{{$default['config']->funcionamento}}</strong></div><div class="bg-white border border-gray-100 rounded-2xl p-5"><div class="w-10 h-10 rounded-xl bg-main/10 text-main flex items-center justify-center"><i class="fa fa-map-marker"></i></div><span class="block text-[10px] uppercase tracking-widest font-black text-gray-400 mt-4">Endereço</span><strong class="block text-sm text-gray-900 mt-1">{{$endereco?:($cidadeNome.($cidadeUf?' - '.$cidadeUf:''))}}</strong></div></div>
<div class="grid lg:grid-cols-2 gap-6 items-stretch">
@if(!empty($default['config']->src_mapa))<div class="bg-white border border-gray-100 rounded-3xl overflow-hidden min-h-[430px] relative"><iframe src="{{$default['config']->src_mapa}}" class="w-full h-full min-h-[430px]" style="border:0" allowfullscreen loading="lazy"></iframe>@if($cidadeNome||$endereco)<div class="absolute left-4 right-4 bottom-4 bg-white/95 backdrop-blur border border-gray-100 rounded-2xl p-4 shadow-lg"><span class="text-[10px] uppercase tracking-widest font-black text-main">Localização</span><strong class="block text-sm text-gray-900 mt-1">{{$cidadeNome}} {{$cidadeUf?'- '.$cidadeUf:''}}</strong>@if($endereco)<span class="block text-xs text-gray-500 mt-1">{{$endereco}}</span>@endif</div>@endif</div>@endif
<div class="bg-white border border-gray-100 rounded-3xl p-6 md:p-8 shadow-sm"><span class="text-[10px] uppercase tracking-[.18em] font-black text-main">Mensagem</span><h2 class="text-2xl font-black text-gray-950 mt-2">Como podemos ajudar?</h2><p class="text-sm text-gray-500 mt-2 mb-6">Preencha os dados e descreva sua dúvida.</p>@if($errors->any())<div class="mb-5 rounded-xl bg-red-50 border border-red-100 p-3 text-sm font-bold text-red-700">{{$errors->first()}}</div>@endif<form method="post" action="/ecommerceContato" class="space-y-4">@csrf<input type="hidden" name="empresa_id" value="{{$default['config']->empresa_id}}"><div class="grid md:grid-cols-2 gap-4"><div><label class="block text-xs font-black text-gray-600 mb-2">Nome</label><input required name="nome" value="{{old('nome')}}" class="w-full h-12 px-4 border border-gray-200 rounded-xl outline-none focus:border-main focus:ring-4 focus:ring-main/10"></div><div><label class="block text-xs font-black text-gray-600 mb-2">E-mail</label><input required name="email" value="{{old('email')}}" type="email" class="w-full h-12 px-4 border border-gray-200 rounded-xl outline-none focus:border-main focus:ring-4 focus:ring-main/10"></div></div><div><label class="block text-xs font-black text-gray-600 mb-2">Mensagem</label><textarea required name="texto" rows="6" class="w-full px-4 py-3 border border-gray-200 rounded-xl outline-none focus:border-main focus:ring-4 focus:ring-main/10 resize-none" placeholder="Escreva sua mensagem">{{old('texto')}}</textarea></div><button type="submit" class="w-full h-12 rounded-xl bg-main text-white text-xs uppercase tracking-wider font-black hover:opacity-90"><i class="fa fa-paper-plane mr-2"></i>Enviar mensagem</button></form></div>
</div></div></section>
@endsection