@extends('ecommerce.default')
@section('content')
<section class="py-8 md:py-12 bg-gray-50/70 min-h-screen"><div class="container mx-auto px-4 max-w-7xl">
<nav class="flex items-center gap-2 text-[10px] uppercase tracking-widest font-black text-gray-400 mb-6"><a href="{{$rota}}" class="hover:text-main">Início</a><span>/</span><span class="truncate">{{$produto->produto->nome}}</span></nav>
<div class="grid lg:grid-cols-2 gap-7 lg:gap-12 items-start"><div class="lg:sticky lg:top-28"><div class="bg-white border border-gray-100 rounded-3xl aspect-square overflow-hidden flex items-center justify-center"><img id="main-image" src="/ecommerce/produtos/{{$produto->galeria[0]->img}}" alt="{{$produto->produto->nome}}" class="w-full h-full object-contain p-5 md:p-8"></div><div class="flex gap-2 mt-3 overflow-x-auto no-scrollbar">@foreach($variacoes as $v)@foreach($v->galeria as $g)<button onclick="changeMainImage('/ecommerce/produtos/{{$g->img}}','{{$v->id}}','{{$v->valor}}')" class="flex-shrink-0 w-20 h-20 rounded-xl border border-gray-100 bg-white hover:border-main p-2"><img src="/ecommerce/produtos/{{$g->img}}" class="w-full h-full object-contain"></button>@endforeach @endforeach</div></div>
<div class="bg-white border border-gray-100 rounded-3xl p-5 md:p-8 shadow-sm"><span class="text-[10px] uppercase tracking-[.16em] font-black text-main">Produto com opções</span><h1 class="text-2xl md:text-4xl font-black text-gray-950 leading-tight tracking-[-.03em] mt-2">{{$produto->produto->nome}}</h1><div class="valor text-3xl md:text-5xl font-black text-gray-950 mt-6">R$ {{number_format($produto->valor,2,',','.')}}</div><div class="text-sm text-gray-600 leading-6 mt-5">{{\Illuminate\Support\Str::limit(trim(strip_tags($produto->descricao)),220)}}</div>
<div class="mt-6"><label class="block text-xs font-black text-gray-600 mb-2">Escolha a opção</label><select class="sel w-full h-12 px-4 border border-gray-200 rounded-xl bg-white outline-none focus:border-main focus:ring-4 focus:ring-main/10">@foreach($variacoes as $v)<option value="{{$v->id}}" data-valor="{{$v->valor}}">{{$v->produto->str_grade}}</option>@endforeach</select></div>
<form method="post" action="{{$rota}}/addProduto" class="mt-5">@csrf<input type="hidden" id="variacoes" value="{{json_encode($variacoes)}}"><input type="hidden" value="{{$default['config']->empresa_id}}" name="empresa_id"><input type="hidden" value="{{$variacoes[0]->id}}" id="produto_id" name="produto_id"><div class="flex flex-col sm:flex-row gap-3"><div class="h-14 flex items-center rounded-2xl border border-gray-200 bg-gray-50"><button type="button" onclick="stepDown()" class="w-12 h-full font-black text-xl">−</button><input id="qtd-input" name="quantidade" type="number" value="1" min="1" class="w-14 bg-transparent text-center outline-none font-black"><button type="button" onclick="stepUp()" class="w-12 h-full font-black text-xl">+</button></div><button class="flex-1 h-14 rounded-2xl bg-main text-white font-black text-xs uppercase tracking-widest"><i class="fa fa-shopping-bag mr-2"></i>Adicionar ao carrinho</button><a href="{{$rota}}/{{$produto->id}}/curtirProduto" class="w-14 h-14 rounded-2xl border border-gray-200 flex items-center justify-center {{$curtida?'text-red-500 bg-red-50 border-red-100':'text-gray-400 hover:text-red-500'}}"><i class="fa fa-heart"></i></a></div></form>
<div class="grid sm:grid-cols-2 gap-3 mt-6">@if($produto->valor_pix>0)<div class="rounded-2xl bg-green-50 border border-green-100 p-4"><span class="text-[10px] uppercase tracking-widest font-black text-green-700">No PIX</span><strong class="block text-lg text-green-800 mt-1">R$ {{number_format($produto->valor_pix,2,',','.')}}</strong></div>@endif @if($produto->valor_cartao>0)<div class="rounded-2xl bg-gray-50 border border-gray-100 p-4"><span class="text-[10px] uppercase tracking-widest font-black text-gray-500">No cartão</span><strong class="block text-lg text-gray-900 mt-1">R$ {{number_format($produto->valor_cartao,2,',','.')}}</strong></div>@endif</div>
</div></div>
<div class="bg-white border border-gray-100 rounded-3xl p-5 md:p-8 mt-7"><h2 class="text-xl font-black text-gray-950 mb-5">Descrição do produto</h2><div class="prose max-w-none text-gray-600 leading-7">{!!$produto->descricao!!}</div></div>
</div></section>
<style>.no-scrollbar::-webkit-scrollbar{display:none}.no-scrollbar{-ms-overflow-style:none;scrollbar-width:none}</style>
@endsection
@section('javascript')
<script>var variacoes=[];$(function(){variacoes=JSON.parse($('#variacoes').val())});function changeMainImage(url,id,valor){$('#main-image').attr('src',url);$('.valor').html('R$ '+formatReal(parseFloat(valor)));$('#produto_id').val(id);$('.sel').val(id)}$('.sel').change(function(){let id=$(this).val(),item=variacoes.find(x=>x.id==id);if(item){$('.valor').html('R$ '+formatReal(parseFloat(item.valor)));$('#produto_id').val(item.id)}});function stepUp(){document.getElementById('qtd-input').stepUp()}function stepDown(){document.getElementById('qtd-input').stepDown()}function formatReal(v){return v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}</script>
@endsection