@extends('ecommerce.default')
@section('content')
<section class="py-10 md:py-14 bg-gray-50/70 min-h-screen"><div class="container mx-auto px-4 max-w-7xl">
<div class="mb-7"><span class="text-[10px] uppercase tracking-[.18em] font-black text-main">Etapa 2 de 3</span><h1 class="text-3xl md:text-4xl font-black tracking-[-.03em] text-gray-950 mt-2">Escolha como receber</h1><p class="text-sm text-gray-500 mt-2">Selecione um endereço e uma opção de entrega.</p></div>
<div class="flex items-center gap-3 mb-7"><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-green-100 text-green-700 flex items-center justify-center text-xs font-black"><i class="fa fa-check"></i></span><span class="text-xs font-black text-gray-500">Carrinho</span></div><div class="h-px flex-1 bg-gray-200"></div><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-main text-white flex items-center justify-center text-xs font-black">2</span><span class="text-xs font-black text-gray-900">Entrega</span></div><div class="h-px flex-1 bg-gray-200"></div><div class="flex items-center gap-2"><span class="w-8 h-8 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center text-xs font-black">3</span><span class="text-xs font-black text-gray-400">Pagamento</span></div></div>
<form method="post" action="{{$rota}}/pagamento" id="shipping-form">@csrf<input type="hidden" id="tipo" name="tipo" value="{{in_array($tipoFrete,['pac','sedex','gratis','retirada'])?$tipoFrete:''}}"><input type="hidden" id="endereco_id" name="endereco_id" value="">
@if(session('flash_erro'))<div class="mb-5 rounded-xl border border-red-100 bg-red-50 p-4 text-red-700 text-sm font-bold">{{session('flash_erro')}}</div>@endif
<div class="grid lg:grid-cols-[minmax(0,1fr)_350px] gap-7 items-start"><div>
<div class="flex items-center justify-between gap-4 mb-4"><div><h2 class="text-lg font-black text-gray-950">Endereços salvos</h2><p class="text-xs text-gray-500 mt-1">Escolha onde deseja receber.</p></div><button type="button" data-toggle="modal" data-target="#modal-endereco" class="inline-flex items-center gap-2 px-4 py-2.5 bg-main text-white rounded-xl text-xs font-black"><i class="fa fa-plus"></i>Novo endereço</button></div>
<div class="space-y-4">@foreach($enderecos as $p)<article class="address-card bg-white border-2 border-gray-100 rounded-2xl p-5 transition-all"><div class="flex gap-3"><div class="w-10 h-10 rounded-xl bg-main/10 text-main flex items-center justify-center flex-shrink-0"><i class="fa fa-map-marker"></i></div><div><strong class="block text-sm text-gray-900">{{$p->rua}}, {{$p->numero}}</strong><span class="block text-xs text-gray-500 mt-1">{{$p->bairro}} · {{$p->cidade}}/{{$p->uf}} · CEP {{$p->cep}}</span></div></div><div class="grid sm:grid-cols-2 gap-2 mt-5">
@if($p->preco_sedex!='0,00')<label class="delivery-option flex items-center gap-3 p-4 rounded-xl border border-gray-200 bg-gray-50 cursor-pointer hover:border-main"><input type="radio" name="opcao_entrega" data-tipo="sedex" data-endereco="{{$p->id}}" data-frete="{{$p->preco_sedex}}" class="w-4 h-4" @checked($tipoFrete==='sedex'&&$loop->first)><span class="flex-1"><strong class="block text-xs text-gray-900">SEDEX</strong><small class="text-[10px] text-gray-500">{{$p->prazo_sedex}} dias</small></span><strong class="text-xs">R$ {{$p->preco_sedex}}</strong></label>@endif
@if($p->preco!='0,00')<label class="delivery-option flex items-center gap-3 p-4 rounded-xl border border-gray-200 bg-gray-50 cursor-pointer hover:border-main"><input type="radio" name="opcao_entrega" data-tipo="pac" data-endereco="{{$p->id}}" data-frete="{{$p->preco}}" class="w-4 h-4" @checked($tipoFrete==='pac'&&$loop->first)><span class="flex-1"><strong class="block text-xs text-gray-900">PAC</strong><small class="text-[10px] text-gray-500">{{$p->prazo}} dias</small></span><strong class="text-xs">R$ {{$p->preco}}</strong></label>@endif
@if($p->frete_gratis)<label class="delivery-option flex items-center gap-3 p-4 rounded-xl border border-green-100 bg-green-50 cursor-pointer hover:border-green-300"><input type="radio" name="opcao_entrega" data-tipo="gratis" data-endereco="{{$p->id}}" data-frete="0" class="w-4 h-4" @checked($tipoFrete==='gratis'&&$loop->first)><span class="flex-1"><strong class="block text-xs text-green-700">Frete grátis</strong><small class="text-[10px] text-green-600">Sem custo de entrega</small></span><strong class="text-xs text-green-700">Grátis</strong></label>@endif
@if($p->habilitar_retirada)<label class="delivery-option flex items-center gap-3 p-4 rounded-xl border border-orange-100 bg-orange-50 cursor-pointer hover:border-orange-300"><input type="radio" name="opcao_entrega" data-tipo="retirada" data-endereco="{{$p->id}}" data-frete="0" class="w-4 h-4" @checked($tipoFrete==='retirada'&&$loop->first)><span class="flex-1"><strong class="block text-xs text-orange-700">Retirar na loja</strong><small class="text-[10px] text-orange-600">Sem frete</small></span><strong class="text-xs text-orange-700">Grátis</strong></label>@endif
</div></article>@endforeach</div>
</div><aside class="lg:sticky lg:top-28"><div class="bg-white border border-gray-100 rounded-3xl p-6 shadow-sm"><h2 class="text-lg font-black text-gray-950">Resumo do pedido</h2><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between text-gray-500"><span>Produtos</span><strong class="text-gray-900">R$ {{number_format($default['carrinho']->somaItens(),2,',','.')}}</strong></div><div class="flex justify-between text-gray-500"><span>Frete</span><strong id="vFrete" class="text-gray-900">R$ 0,00</strong></div><div class="pt-4 mt-4 border-t border-gray-100 flex justify-between items-end"><span class="font-black text-gray-900">Total</span><strong id="vTotal" class="text-2xl font-black text-main">R$ {{number_format($default['carrinho']->somaItens(),2,',','.')}}</strong></div></div><input type="hidden" id="total" value="{{$default['carrinho']->somaItens()}}"><button id="btn-pagar" type="submit" class="w-full mt-6 h-13 py-4 bg-main text-white rounded-2xl font-black text-xs uppercase tracking-wider hover:opacity-90">Continuar para pagamento <i class="fa fa-arrow-right ml-2"></i></button><p id="entrega-aviso" class="text-center text-xs text-red-500 mt-3 font-bold">Selecione uma opção de entrega.</p><a href="{{$rota}}/carrinho" class="mt-4 flex items-center justify-center text-xs font-black text-gray-500 hover:text-main"><i class="fa fa-arrow-left mr-2"></i>Voltar ao carrinho</a></div></aside></div></form>
</div></section>
@section('javascript')
<script>$(function(){const total=parseFloat($('#total').val()||0);function valorNumero(v){v=String(v||'0').trim();if(v.includes(',')&&v.includes('.'))v=v.replace(/\./g,'').replace(',','.');else v=v.replace(',','.');return parseFloat(v)||0}function moeda(v){return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function aplicar(){const s=$('input[name="opcao_entrega"]:checked');if(!s.length){$('#tipo,#endereco_id').val('');$('#entrega-aviso').show();return false}const t=s.data('tipo'),e=s.data('endereco'),f=valorNumero(s.data('frete'));$('#tipo').val(t);$('#endereco_id').val(e);$('#vFrete').text(moeda(f));$('#vTotal').text(moeda(total+f));$('#entrega-aviso').hide();$('.address-card').removeClass('border-main shadow-md');s.closest('.address-card').addClass('border-main shadow-md');$('.delivery-option').removeClass('ring-2 ring-main');s.closest('.delivery-option').addClass('ring-2 ring-main');return true}$('input[name="opcao_entrega"]').on('change',aplicar);aplicar();$('#shipping-form').on('submit',function(e){if(!aplicar()){e.preventDefault();swal('Atenção','Selecione um endereço e uma forma de entrega antes de continuar.','warning');return false}$('#btn-pagar').prop('disabled',true).text('Preparando pagamento...')})});</script>
@endsection
@endsection